info:
  version: 1.0.2
  description: UDR initial local configuration

configuration:
  sbi: # Service-based interface information
    scheme: http # the protocol for sbi (http or https)
    registerIPv4: 10.10.0.83 # IP used to register to NRF
    bindingIPv4: 10.10.0.83  # IP used to bind the service
    port: 8008 # port used to bind the service
    tls: # the local path of TLS key
      pem: cert/udr.pem # UDR TLS Certificate
      key: cert/udr.key # UDR TLS Private key
  mongodb:
    name: free5gc # Database name in MongoDB
    url: mongodb://localhost:27017 # URL of MongoDB
  nrfUri: http://10.10.0.83:8003 # a valid URI of NRF
  nrfCertPem: cert/nrf.pem # NRF Certificate

logger: # log output setting
  enable: true # true or false
  level: info # how detailed to output, value: trace, debug, info, warn, error, fatal, panic
  reportCaller: false # enable the caller report or not, value: true or false
